Changed radius start script to LSBINIT

diff --git a/plugins/debian_8_x64 b/plugins/debian_8_x64
--- a/plugins/debian_8_x64
+++ b/plugins/debian_8_x64
@@ -100,143 +100,74 @@ _install_freeradius() {
 	echo "_________________________________________________________________"
 	echo " RADIUS SCRIPT AUTOSTART"
 	echo "_________________________________________________________________"
-	cat << 'EOF' > /etc/init.d/radiusd
+	cat << 'EOF' > /etc/init.d/freeradius
 #!/bin/sh
-#
-# radiusd	Start the radius daemon.
-#
-#    This program is free software; you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation; either version 2 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License
-#    along with this program; if not, write to the Free Software
-#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
-#
-#    Copyright (C) 2001-2008 The FreeRADIUS Project http://www.freeradius.org
-#   chkconfig: - 58 74
-#   description: radiusd is service access provider Daemon.
+# Start/stop the FreeRADIUS daemon.
+
 ### BEGIN INIT INFO
-# Provides: radiusd
-# Should-Start: radiusd
-# Should-Stop: radiusd
-# Short-Description: start and stop radiusd
-# Description: radiusd is access provider service Daemon.
+# Provides:          freeradius
+# Required-Start:    $remote_fs $network $syslog
+# Should-Start:      $time mysql slapd postgresql samba krb5-kdc
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Radius Daemon
+# Description:       Extensible, configurable radius daemon
 ### END INIT INFO
 
-prefix=/usr/local/freeradius
-exec_prefix=${prefix}
-sbindir=${exec_prefix}/sbin
-localstatedir=/var
-logdir=${localstatedir}/log/radius
-rundir=/usr/local/freeradius/var/run/radiusd/
-sysconfdir=${prefix}/etc
-#
-#  If you have issues with OpenSSL, uncomment these next lines.
-#
-#  Something similar may work for MySQL, and you may also
-#  have to LD_PRELOAD libz.so
-#
-#LD_LIBRARY_PATH=
-#LD_RUN_PATH=:
-#LD_PRELOAD=libcrypto.so
-export LD_LIBRARY_PATH LD_RUN_PATH LD_PRELOAD
+set -e
 
-RADIUSD=$sbindir/radiusd
-RADDBDIR=${sysconfdir}/raddb
-RADIUS_USER='freerad'
-DESC="FreeRADIUS"
+. /lib/lsb/init-functions
 
-#
-#  See 'man radiusd' for details on command-line options.
-#
-ARGS=""
+PROG="freeradius"
+PROGRAM="/usr/sbin/radiusd"
+PIDFILE="/var/run/radiusd/radiusd.pid"
+DESCR="FreeRADIUS daemon"
 
-test -f $RADIUSD || exit 0
-test -f $RADDBDIR/radiusd.conf || exit 0
+test -f $PROGRAM || exit 0
 
-if [ ! -d $rundir ] ; then
-    mkdir $rundir
-    chown ${RADIUS_USER}:${RADIUS_USER} $rundir
-    chmod 775 $rundir
+# /var/run may be a tmpfs
+if [ ! -d /var/run/radiusd ]; then
+ mkdir -p /var/run/radiusd
+ chown freerad:freerad /var/run/radiusd
 fi
 
-if [ ! -d $logdir ] ; then
-    mkdir $logdir
-    chown ${RADIUS_USER}:${RADIUS_USER} $logdir
-    chmod 770 $logdir
-    chmod g+s $logdir
-fi
+export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
-if [ ! -f $logdir/radius.log ]; then
-        touch $logdir/radius.log
-fi
-
-chown ${RADIUS_USER}:${RADIUS_USER} $logdir/radius.log
-chown -R ${RADIUS_USER}:${RADIUS_USER} /usr/local/freeradius/etc/raddb
-chown -R ${RADIUS_USER}:${RADIUS_USER} ${rundir}
-chmod 660 $logdir/radius.log
+ret=0
 
 case "$1" in
-  start)
-	echo -n "Starting $DESC:"
-	$RADIUSD $ARGS
-	echo "radiusd"
-	;;
-  stop)
-	[ -z "$2" ] && echo -n "Stopping $DESC: "
-        [ -f $rundir/radiusd.pid ] && kill -TERM `cat $rundir/radiusd.pid`
-	[ -z "$2" ] && echo "radiusd."
-	;;
-  reload|force-reload)
-	echo "Reloading $DESC configuration files."
-	[ -f $rundir/radiusd.pid ] && kill -HUP `cat $rundir/radiusd.pid`
-	;;
-  restart)
-	sh $0 stop quiet
-	sleep 3
-	sh $0 start
-	;;
-  check)
-	$RADIUSD -CX $ARGS
-	exit $?
-	;;
-  *)
-        echo "Usage: /etc/init.d/$RADIUS {start|stop|reload|restart|check}"
-        exit 1
-        stop
-        ;;
-  status)
-        status \$prog
-        ;;
-  restart|force-reload)
-        stop
-        start
-        ;;
-  try-restart|condrestart)
-        if status \$prog > /dev/null; then
-            stop
-            start
-        fi
-        ;;
-  reload)
-        exit 3
-        ;;
-  *)
-        echo \$"Usage: \$0 {start|stop|status|restart|try-restart|force-reload}"
-        exit 2
+        start)
+                log_daemon_msg "Starting $DESCR" "$PROG"
+                start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $PROGRAM || ret=$?
+                log_end_msg $ret
+                exit $ret
+                ;;
+        stop)
+                log_daemon_msg "Stopping $DESCR" "$PROG"
+                if [ -f "$PIDFILE" ] ; then
+                  start-stop-daemon --stop --retry=TERM/30/KILL/5 --quiet --pidfile $PIDFILE || ret=$?
+                  log_end_msg $ret
+                else
+                  log_action_cont_msg "$PIDFILE not found"
+                  log_end_msg 0
+                fi
+                ;;
+        restart|force-reload)
+                $0 stop
+                $0 start
+                ;;
+        *)
+                echo "Usage: $0 start|stop|restart|force-reload"
+                exit 1
+                ;;
 esac
 
+exit 0
 EOF
 
-	chmod +x /etc/init.d/radiusd
-	update-rc.d radiusd defaults
+	chmod +x /etc/init.d/freeradius
+	update-rc.d freeradius defaults
 	cd ${CURRENT_DIR}
 }
 
